### ISSUE TITLE
release prettier-plugin-toml 0.3.2 to npmjs

### ISSUE THREAD

**Issue by bobbui** [un-ts/toml-tools#42]
Could you please release latest code for prettier-plugin-toml to npmjs.
Currently 0.3.1 having this error:
```
 TypeError: Cannot read property 'tokenTypeIdx' of undefined
    at /project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/scan/tokens.js:91:78
    at Object.forEach (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/utils/utils.js:85:30)
    at /project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/scan/tokens.js:90:17
    at Object.forEach (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/utils/utils.js:77:30)
    at assignCategoriesTokensProp (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/scan/tokens.js:87:13)
    at Object.augmentTokenTypes (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/scan/tokens.js:32:5)
    at TomlParser.RecognizerEngine.initRecognizerEngine (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/parse/parser/traits/recognizer_engine.js:86:18)
    at new Parser (/project/node_modules/@toml-tools/parser/node_modules/chevrotain/lib/src/parse/parser/parser.js:69:14)
    at new TomlParser (/project/node_modules/@toml-tools/parser/lib/parser.js:6:5)
    at Object.<anonymous> (/project/node_modules/@toml-tools/parser/lib/api.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Module._compile (/usr/local/lib/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/cx/hqb2r_t50q7761ls_dp99qzm00011z/T/ts-node-dev-hook-6387655258481435.js:114:20)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/project/node_modules/prettier-plugin-toml/lib/api.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Module._compile (/usr/local/lib/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/cx/hqb2r_t50q7761ls_dp99qzm00011z/T/ts-node-dev-hook-6387655258481435.js:114:20)
    at Object.nodeDevHook [as .js] (/usr/local/lib/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /project/node_modules/prettier/index.js:57503:6
    at Array.map (<anonymous>)
    at Object.load (/project/node_modules/prettier/index.js:57501:118)
    at Object.load [as loadPlugins] (/project/node_modules/prettier/index.js:16612:23)
    at /project/node_modules/prettier/index.js:57540:28
    at Object.format (/project/node_modules/prettier/index.js:57562:12)
```

Thanks in advanced

**Comment by bd82** [comment]
Hi @bobbui I no longer have time to maintain this package.
See #43 if you are interested in taking over.
